PT-2262: Update Shipping module
VirtoCommerce/vc-module-shipping pull request #24
Opened 2021-08-20 12:40 UTC by BelyakovSergey

## Description
Implement generic CRUD service
## References
### QA-test:
### Jira-link:
https://virtocommerce.atlassian.net/browse/PT-2262
### Artifact URL:

2021-08-20 12:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-module-shipping?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-module-shipping?pullRequest=24) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-module-shipping?pullRequest=24) it.</sub>

2021-08-23 09:33 UTC, eMazeika commented on src/VirtoCommerce.ShippingModule.Data/VirtoCommerce.ShippingModule.Data.csproj
> +    </ItemGroup>
remove empty folder

2021-08-23 09:33 UTC, eMazeika commented on tests/VirtoCommerce.ShippingModule.Data.Tests/VirtoCommerce.ShippingModule.Data.Tests.csproj
> +    <PackageReference Include="coverlet.collector" Version="3.1.0">
revert back to 1.3.0

2021-08-23 09:33 UTC, eMazeika commented on tests/VirtoCommerce.ShippingModule.Data.Tests/VirtoCommerce.ShippingModule.Tests.csproj
> +    <PackageReference Include="coverlet.collector" Version="3.1.0">
1.3.0

2021-08-23 12:18 UTC, BelyakovSergey commented on tests/VirtoCommerce.ShippingModule.Data.Tests/VirtoCommerce.ShippingModule.Tests.csproj
> +    <PackageReference Include="coverlet.collector" Version="3.1.0">
Fixed

2021-08-23 16:36 UTC, akak1977 requested changes

2021-08-23 16:36 UTC, akak1977 commented on src/VirtoCommerce.ShippingModule.Core/Services/IShippingMethodsSearchService.cs
>      }
There the compatibility will be broken. Need to preserve original interface.

2021-08-23 16:36 UTC, akak1977 commented on src/VirtoCommerce.ShippingModule.Core/Services/IShippingMethodsService.cs
>      public interface IShippingMethodsService
Ensure these removed methods are signature compatible with existing ones from ICrudService. Otherwise, compatibility will be broken.

2021-08-31 11:20 UTC, closed without merging